include(MathLibs)
include(MathLibsFunctions)

set(MATH_LANG "Fortran")

if(ENABLE_BUILTIN_BLAS)
    if(ENABLE_AUTO_BLAS)
        message(FATAL_ERROR "ENABLE_BUILTIN_BLAS and ENABLE_AUTO_BLAS together makes no sense")
    endif()
    set(USE_BUILTIN_BLAS TRUE)
    message("-- BLAS: using builtin implementation (slow)")
else()
    set(USE_BUILTIN_BLAS FALSE)
endif()

if(DEFINED EXPLICIT_BLAS_LIB)
    if(ENABLE_AUTO_BLAS)
        message(FATAL_ERROR "EXPLICIT_BLAS_LIB and ENABLE_AUTO_BLAS together makes no sense")
    endif()
    if(ENABLE_BUILTIN_BLAS)
        message(FATAL_ERROR "EXPLICIT_BLAS_LIB and ENABLE_BUILTIN_BLAS together makes no sense")
    endif()
    set(EXTERNAL_LIBS
        ${EXTERNAL_LIBS}
        ${EXPLICIT_BLAS_LIB}
        )
    message("-- BLAS: using explit library (${EXPLICIT_BLAS_LIB})")
endif()

if(ENABLE_BUILTIN_LAPACK)
    if(ENABLE_AUTO_LAPACK)
        message(FATAL_ERROR "ENABLE_BUILTIN_LAPACK and ENABLE_AUTO_LAPACK together makes no sense")
    endif()
    set(USE_BUILTIN_LAPACK TRUE)
    message("-- LAPACK: using builtin implementation (slow)")
else()
    set(USE_BUILTIN_LAPACK FALSE)
endif()

if(DEFINED EXPLICIT_LAPACK_LIB)
    if(ENABLE_AUTO_LAPACK)
        message(FATAL_ERROR "EXPLICIT_LAPACK_LIB and ENABLE_AUTO_LAPACK together makes no sense")
    endif()
    if(ENABLE_BUILTIN_LAPACK)
        message(FATAL_ERROR "EXPLICIT_LAPACK_LIB and ENABLE_BUILTIN_LAPACK together makes no sense")
    endif()
    set(EXTERNAL_LIBS
        ${EXTERNAL_LIBS}
        ${EXPLICIT_LAPACK_LIB}
        )
    message("-- LAPACK: using explit library (${EXPLICIT_LAPACK_LIB})")
endif()

if(ENABLE_CRAY_WRAPPERS)
    if(ENABLE_BUILTIN_BLAS)
        message(FATAL_ERROR "ENABLE_CRAY_WRAPPERS and ENABLE_BUILTIN_BLAS together makes no sense")
    endif()
    if(ENABLE_AUTO_BLAS)
        message(FATAL_ERROR "ENABLE_CRAY_WRAPPERS and ENABLE_AUTO_BLAS together makes no sense")
    endif()
    if(ENABLE_BUILTIN_LAPACK)
        message(FATAL_ERROR "ENABLE_CRAY_WRAPPERS and ENABLE_BUILTIN_LAPACK together makes no sense")
    endif()
    if(ENABLE_AUTO_LAPACK)
        message(FATAL_ERROR "ENABLE_CRAY_WRAPPERS and ENABLE_AUTO_LAPACK together makes no sense")
    endif()
    message("-- Use CRAY wrappers; this disables math detection and builtin math libraries")
endif()

if(DEFINED MKL_FLAG)
    if(ENABLE_BUILTIN_BLAS)
        message(FATAL_ERROR "MKL_FLAG and ENABLE_BUILTIN_BLAS together makes no sense")
    endif()
    if(ENABLE_AUTO_BLAS)
        message(FATAL_ERROR "MKL_FLAG and ENABLE_AUTO_BLAS together makes no sense")
    endif()
    if(ENABLE_BUILTIN_LAPACK)
        message(FATAL_ERROR "MKL_FLAG and ENABLE_BUILTIN_LAPACK together makes no sense")
    endif()
    if(ENABLE_AUTO_LAPACK)
        message(FATAL_ERROR "MKL_FLAG and ENABLE_AUTO_LAPACK together makes no sense")
    endif()
    set(EXTERNAL_LIBS
        ${EXTERNAL_LIBS}
        ${MKL_FLAG}
        )
    message("-- User set explicit MKL flag which is passed to the compiler and linker: ${MKL_FLAG}")
    message("-- This disables math detection and builtin math libraries")
endif()

if(ENABLE_AUTO_BLAS)
    config_math_service(BLAS)
endif()

if(ENABLE_AUTO_LAPACK)
    config_math_service(LAPACK)
endif()
